#!/usr/bin/env python3
"""Deprecated helper from the previous archetype family.

The active repository archetypes are now the no-minutes k8 run with fixed k6
drop5/7 labels:

1. Low Usage Connector
2. Rim Protecting Big
3. Lead Guard
4. Defensive Spacer
5. Scoring Big
6. Pure Shooter

Use ``scripts/promote_no_minutes_archetypes.py`` to refresh active artifacts.
This module exits immediately so the previous label family cannot be
regenerated by accident.
"""


def main() -> int:
    raise SystemExit(
        "Deprecated: active archetypes are k6_no_minutes_drop5_7. "
        "Run scripts/promote_no_minutes_archetypes.py instead."
    )


if __name__ == "__main__":
    main()
